"""empty message

Revision ID: e9db4c603d8f
Revises: 5e40cfa54701
Create Date: 2021-05-04 13:51:21.597214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9db4c603d8f'
down_revision = '5e40cfa54701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'activities', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_column('activities', 'user_id')
    # ### end Alembic commands ###
